apps/niza/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import HomeTemplateView, log_out, ProjectListView, ProjectDetailView, RateTemplateView
from .views import SendRate
app_name = 'niza'


router = DefaultRouter()
router.register(r'rating', SendRate)


urlpatterns = [
    path('', include(router.urls)),
    path('home/', HomeTemplateView.as_view(), name='home'),
    path('rate/', RateTemplateView.as_view(), name='rate'),
    path('log_out/', log_out, name='log_out'),
    path('projects/', ProjectListView.as_view(), name='projects'),
    path('project/<int:pk>/', ProjectDetailView.as_view(), name='project')

]

apps/third_party_apps/fcm/urls.py
from django.conf.urls import url

from . import views

urlpatterns = (
    url(r'^devices/$', views.DeviceList.as_view(), name='device_list'),
    url(r'^devices/(?P<pk>[0-9]+)/$', views.DeviceDetail.as_view(),
        name='device_detail'),
    url(r'^send/$', views.FCMList.as_view(), name='fcm_send'),
)

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.conf import settings
from rest_framework_swagger.views import get_swagger_view
from rest_framework.routers import DefaultRouter
from apps.niza.views import log_in, HomeTemplateView

router = DefaultRouter()

schema_view = get_swagger_view(title='osw4l api 2.0')

urlpatterns = [
    path('login/', log_in, name='sign_in'),
    path('', HomeTemplateView.as_view()),
    path('admin/', admin.site.urls),
    path('niza/', include('apps.niza.urls', namespace='niza')),
    path('api/', include(router.urls)),
    path('admin/statuscheck/', include('celerybeat_status.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>Niza</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/pricing/">

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.5/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <link rel="stylesheet" href="https://antennaio.github.io/jquery-bar-rating/dist/themes/fontawesome-stars.css">
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        hr {
            margin-top: 1rem;
            margin-bottom: 1rem;
            border: 0;
            border-top: 1px solid rgba(0, 0, 0, 0.1);
        }

        .btn:focus, .btn:active, button:focus, button:active {
            outline: none !important;
            box-shadow: none !important;
        }

        #image-gallery .modal-footer {
            display: block;
        }

        .thumb {
            margin-top: 15px;
            margin-bottom: 15px;
        }

        .br-theme-fontawesome-stars .br-widget a {
            font: normal normal normal 46px/1 FontAwesome !important;
            text-rendering: auto;
            -webkit-font-smoothing: antialiased;
            text-decoration: none;
            margin-right: 2px;
        }

        .br-theme-fontawesome-stars .br-widget a:after {
            content: '\f006';
            color: #d2d2d2;
        }

        .br-theme-fontawesome-stars .br-widget a.br-selected:after {
            color: #FFD739 !important;
        }

        .br-theme-fontawesome-stars .br-widget a.br-active:after {
            color: #FFD739 !important;
        }
    </style>

</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal">Niza</h5>
    <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark" href="{% url 'niza:home' %}">Inicio</a>
        <a class="p-2 text-dark" href="{% url 'niza:projects' %}">Lista de proyectos</a>
        <a class="p-2 text-dark" href="#">
            Usuario: <strong>{{ request.user.username }}</strong>
        </a>
    </nav>
    <a class="btn btn-outline-danger" href="{% url 'niza:log_out' %}">
        Cerrar Sesión
    </a>
</div>


{% block main %}
{% endblock main %}

<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>


{% block script %}
{% endblock %}

</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block main %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Bienvenido a niza</h1>
        <p class="lead">
            Seleccione una opcion
        </p>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-2">
                <div class="card mb-4 shadow-sm text-center">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal text-center">Proyectos</h4>
                    </div>
                    <div class="card-body">
                        <img src="{% static 'project.png' %}" alt="" width="200px" height="160px">
                        <a href="{% url 'niza:projects' %}" class="btn btn-block btn-outline-success mt-2">
                            Ir a proyectos
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card mb-4 shadow-sm text-center">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal text-center">Calificación</h4>
                    </div>
                    <div class="card-body">
                        <img src="{% static 'rate.png' %}" alt="" width="200px" height="160px">
                        <a href="{% url 'niza:rate' %}" class="btn btn-block btn-warning mt-2">
                            Califica la plataforma <i class="fa fa-star"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/login.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>Niza - Login</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/sign-in/">

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.5/dist/css/bootstrap.min.css" rel="stylesheet">
    <meta name="theme-color" content="#563d7c">
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

         .btn-primary {
            color: #fff;
            background-color: #31a0ad;
            border-color: #36a8b3;
        }

        .btn-primary:hover {
            color: #fff;
            background-color: #215f69;
            border-color: #2d91a0;
        }
    </style>
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.5/examples/sign-in/signin.css" rel="stylesheet">
</head>
<body class="text-center">
<form class="form-signin" method="post">{% csrf_token %}
    <img class="mb-4" src="{% static 'niza.png' %}" alt="" width="72" height="72">
    <h1 class="h3 mb-3 font-weight-normal">
        Bienvenido a Niza
    </h1>
    {% if msj %}
    <div class="alert alert-danger">
        <strong>{{ msj }}</strong>
    </div>
    {% endif %}
    <label for="inputEmail" class="sr-only">Usuario</label>
    <input name="username" type="text" id="inputEmail" class="form-control" placeholder="Su usuario" required autofocus>
    <label for="inputPassword" class="sr-only">Constraseña</label>
    <input name="password" type="password" id="inputPassword" class="form-control" placeholder="Su contraseña" required>
    <button class="btn btn-lg btn-primary btn-block" type="submit">
        Iniciar Sesión
    </button>
    <p class="mt-5 mb-3 text-muted">&copy; 2020</p>
</form>
</body>
</html>

templates/rate.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block main %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        {% if request.user.customer.count_reviews == 0 %}
            <h1 class="display-4">¿Qué te ha parecido?</h1>
            <p class="lead">
                Califica nuestra plataforma
            </p>
        {% else %}
            <h1 class="display-4">Gracias por tu comentario</h1>
            <p class="lead">
                hemos recibido con exito tu calificacion
            </p>
        {% endif %}
    </div>
    <div class="container">
        {% if request.user.customer.count_reviews == 0 %}
            <div class="row">
                <div class="col-md-4 offset-md-4">
                    <div class="card mb-4 shadow-sm">
                        <div class="card-body">
                            <div class="form-group">
                                <input type="text" id="title" placeholder="Nombre" class="form-control">
                            </div>
                            <div class="form-group">
                                <input type="text" id="position" placeholder="Cargo" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="comment" class="text-left">
                                    Deja tu comentario
                                </label>
                                <textarea id="comment" class="form-control" placeholder="Deja tu comentario"
                                          rows="2"></textarea>
                            </div>
                            <div class="form-group">
                                <label for="rating" class="text-left">Tu calificación</label>
                                <div align="center">
                                    <select id="rating" style="margin-right: auto; margin-right: auto">
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                        <option value="4">4</option>
                                        <option value="5">5</option>
                                    </select>
                                </div>
                            </div>
                            <button class="btn btn-outline-info btn-block mt-5" id="send">
                                Enviar calificacion
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

{% block script %}
    <script src="https://antennaio.github.io/jquery-bar-rating/dist/jquery.barrating.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $('#rating').barrating({
                theme: 'fontawesome-stars'
            });

            $('#send').click(function (e) {
                const title = $('#title').val();
                const position = $('#position').val();
                const comment = $('#comment').val();
                const score = parseInt($('#rating').val());

                const data = {
                    title,
                    position,
                    comment,
                    score
                };

                $.ajax({
                    url: window.location.origin + "/niza/rating/",
                    method: 'POST', //First change type to method here
                    data,
                    success: function (response) {
                        swal("Good job!", "You clicked the button!", "success");
                        setTimeout(() => {
                            window.location.reload();
                        }, 2000);
                    },
                    error: function () {
                        swal("error", "it cannot save the review :( !", "error");
                    }

                });

            });

        });
    </script>
{% endblock %}